### ISSUE TITLE
DEV  MVP 4 - Update couchdb version in u16all from 1.6.1 to 2.0.0

### ISSUE THREAD

**Issue by rai-sushmitha** [dry-dock/u16all#21] opened 2017-07-11 08:26 UTC
from https://github.com/Shippable/pm/issues/8613

**Comment by kanthchandra** [comment] 2017-07-11 13:21
duplicate of https://github.com/dry-dock/u16all/issues/31

**Closed by kanthchandra** 2017-07-11 13:21 UTC
